package com.tsubasa.core_compiler.utils;

/**
 * Created by tsubasa on 2017/11/15.
 */

public class Consts {
    // Generate
    public static final String SEPARATOR = "$$";
    public static final String PROJECT = "TsBaseCore";
    public static final String METHOD_LOAD_INTO = "loadInto";
    public static final String NAME_OF_ROOT = PROJECT + SEPARATOR + "Root";
    public static final String NAME_OF_GROUP = PROJECT + SEPARATOR + "Group" + SEPARATOR;
    public static final String PACKAGE_OF_GENERATE_FILE = "com.tsubasa.core.app.di.routes";
    public static final String WARNING_TIPS = "DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY TsBaseCore.";

    // Options of processor
    public static final String KEY_MODULE_NAME = "moduleName";


    // Custom interface
    private static final String FACADE_PACKAGE = "com.tsubasa.core";
    private static final String TEMPLATE_PACKAGE = ".template";
    public static final String ITROUTE_ROOT = FACADE_PACKAGE + TEMPLATE_PACKAGE + ".IRouteRoot";
    public static final String IROUTE_GROUP = FACADE_PACKAGE + TEMPLATE_PACKAGE + ".IRouteGroup";


    // Annotation type
    public static final String ANNOTATION_TYPE_INJECTABLE = FACADE_PACKAGE + ".common.annotation.Injectable";

    // Log
    public static final String PREFIX_OF_LOGGER = PROJECT + "::Compiler ";

    // System interface
    public static final String ACTIVITY = "android.app.Activity";
    public static final String FRAGMENT = "android.app.Fragment";
    public static final String FRAGMENT_V4 = "android.support.v4.app.Fragment";
    public static final String SERVICE = "android.app.Service";
}
